[workspace]
members = [
  'codegen',
  'coreml-proto',
]
resolver = "2"


[workspace.dependencies]
codegen = { path = "./codegen" }
prost = "0.14"
prost-build = "0.14"
prost-types = "0.14"


[workspace.package]
authors = ["Eric Saxby <sax@reflective.dev>", "synchronal.dev"]
description = "CoreML protobuf definitions and decoders"
edition = "2024"
homepage = "https://github.com/synchronal/coreml-proto"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/synchronal/coreml-proto"
rust-version = "1.89"
version = "0.1.0"
