[workspace]
members = [
  'codegen',
  'coreml-proto',
]
resolver = "2"


[workspace.dependencies]


[workspace.package]
authors = ["Eric Saxby <sax@reflective.dev>", "synchronal.dev"]
description = "CoreML protobuf definitions and model introspection library"
edition = "2024"
homepage = "https://github.com/synchronal/coreml-proto"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/synchronal/coreml-proto"
rust-version = "1.89"
version = "0.1.0"

