[package]
name = "codegen"
authors.workspace = true
description = "Code generation for coreml-proto"
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]


[build-dependencies]
prost-build = { workspace = true }

