// This file is @generated by prost-build.
///
/// A model which takes an input audio and outputs array(s) of features
/// according to the specified feature types
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AudioFeaturePrint {
    /// Audio feature print type
    #[prost(oneof = "audio_feature_print::AudioFeaturePrintType", tags = "20")]
    pub audio_feature_print_type: ::core::option::Option<
        audio_feature_print::AudioFeaturePrintType,
    >,
}
/// Nested message and enum types in `AudioFeaturePrint`.
pub mod audio_feature_print {
    /// Sound extracts features useful for identifying the predominant
    /// sound in audio signal
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Sound {
        #[prost(enumeration = "sound::SoundVersion", tag = "1")]
        pub version: i32,
    }
    /// Nested message and enum types in `Sound`.
    pub mod sound {
        #[allow(clippy::all)]
        #[allow(clippy::pedantic)]
        #[allow(clippy::nursery)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum SoundVersion {
            Invalid = 0,
            /// VERSION_1 is available on iOS,tvOS 15.0+, macOS 12.0+
            /// It uses a variable-length input audio sample vector and yields a 512 float feature vector
            SoundVersion1 = 1,
        }
        impl SoundVersion {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Invalid => "SOUND_VERSION_INVALID",
                    Self::SoundVersion1 => "SOUND_VERSION_1",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "SOUND_VERSION_INVALID" => Some(Self::Invalid),
                    "SOUND_VERSION_1" => Some(Self::SoundVersion1),
                    _ => None,
                }
            }
        }
    }
    /// Audio feature print type
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum AudioFeaturePrintType {
        #[prost(message, tag = "20")]
        Sound(Sound),
    }
}
///
/// A model which maps a set of strings into a finite-dimensional real vector space.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WordEmbedding {
    ///
    /// Stores the revision number for the model, revision 2 is available on
    /// iOS, tvOS 13.0+, macOS 10.15+
    #[prost(uint32, tag = "1")]
    pub revision: u32,
    ///
    /// Stores the language of the model, as specified in BCP-47 format,
    /// e.g. "en-US". See <https://tools.ietf.org/html/bcp47>
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    ///
    /// Stores efficient representation of emebedding as encoded by the Natural Language Framework
    #[prost(bytes = "vec", tag = "100")]
    pub model_parameter_data: ::prost::alloc::vec::Vec<u8>,
}
///
/// A model which uses an efficient probabilistic representation
/// for assigning labels to a set of strings.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Gazetteer {
    ///
    /// Stores the revision number for the model, revision 2 is available on
    /// iOS, tvOS 13.0+, macOS 10.15+
    #[prost(uint32, tag = "1")]
    pub revision: u32,
    ///
    /// Stores the language of the model, as specified in BCP-47 format,
    /// e.g. "en-US". See <https://tools.ietf.org/html/bcp47>
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    ///
    /// Natural Language framework's efficient representation of a gazetter.
    #[prost(bytes = "vec", tag = "100")]
    pub model_parameter_data: ::prost::alloc::vec::Vec<u8>,
    ///
    /// Stores the set of output class labels
    #[prost(oneof = "gazetteer::ClassLabels", tags = "200")]
    pub class_labels: ::core::option::Option<gazetteer::ClassLabels>,
}
/// Nested message and enum types in `Gazetteer`.
pub mod gazetteer {
    ///
    /// Stores the set of output class labels
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ClassLabels {
        #[prost(message, tag = "200")]
        StringClassLabels(super::super::StringVector),
    }
}
///
/// A model which takes an input image and outputs array(s) of features
/// according to the specified feature types
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VisionFeaturePrint {
    /// Vision feature print type
    #[prost(oneof = "vision_feature_print::VisionFeaturePrintType", tags = "20, 21")]
    pub vision_feature_print_type: ::core::option::Option<
        vision_feature_print::VisionFeaturePrintType,
    >,
}
/// Nested message and enum types in `VisionFeaturePrint`.
pub mod vision_feature_print {
    /// Scene extracts features useful for identifying contents of natural images
    /// in both indoor and outdoor environments
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Scene {
        #[prost(enumeration = "scene::SceneVersion", tag = "1")]
        pub version: i32,
    }
    /// Nested message and enum types in `Scene`.
    pub mod scene {
        #[allow(clippy::all)]
        #[allow(clippy::pedantic)]
        #[allow(clippy::nursery)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum SceneVersion {
            Invalid = 0,
            /// VERSION_1 is available on iOS,tvOS 12.0+, macOS 10.14+
            /// It uses a 299x299 input image and yields a 2048 float feature vector
            SceneVersion1 = 1,
            /// VERSION_2 is available on iOS,tvOS 17.0+, macOS 14.0+
            /// It uses a 360x360 input image and yields a 768 float feature vector
            SceneVersion2 = 2,
        }
        impl SceneVersion {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Invalid => "SCENE_VERSION_INVALID",
                    Self::SceneVersion1 => "SCENE_VERSION_1",
                    Self::SceneVersion2 => "SCENE_VERSION_2",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "SCENE_VERSION_INVALID" => Some(Self::Invalid),
                    "SCENE_VERSION_1" => Some(Self::SceneVersion1),
                    "SCENE_VERSION_2" => Some(Self::SceneVersion2),
                    _ => None,
                }
            }
        }
    }
    /// Objects extracts features useful for identifying and localizing
    /// objects in natural images
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Objects {
        #[prost(enumeration = "objects::ObjectsVersion", tag = "1")]
        pub version: i32,
        ///
        /// Stores the names of the output features according to the
        /// order of them being computed from the neural network, i.e.,
        /// the first element in the output is the earliest being
        /// computed, while the last is the latest being computed. In
        /// general, the order reflects the resolution of the feature.
        /// The earlier it is computed, the higher the feature resolution.
        #[prost(string, repeated, tag = "100")]
        pub output: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    /// Nested message and enum types in `Objects`.
    pub mod objects {
        #[allow(clippy::all)]
        #[allow(clippy::pedantic)]
        #[allow(clippy::nursery)]
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum ObjectsVersion {
            Invalid = 0,
            /// VERSION_1 is available on iOS,tvOS 14.0+, macOS 11.0+
            /// It uses a 299x299 input image and yields two multiarray
            /// features: one at high resolution of shape (288, 35, 35)
            /// the other at low resolution of shape (768, 17, 17)
            ObjectsVersion1 = 1,
        }
        impl ObjectsVersion {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Invalid => "OBJECTS_VERSION_INVALID",
                    Self::ObjectsVersion1 => "OBJECTS_VERSION_1",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "OBJECTS_VERSION_INVALID" => Some(Self::Invalid),
                    "OBJECTS_VERSION_1" => Some(Self::ObjectsVersion1),
                    _ => None,
                }
            }
        }
    }
    /// Vision feature print type
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum VisionFeaturePrintType {
        #[prost(message, tag = "20")]
        Scene(Scene),
        #[prost(message, tag = "21")]
        Objects(Objects),
    }
}
///
/// A model which takes a single input string and outputs a
/// label for the input.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextClassifier {
    ///
    /// Stores the resivion number for the model, revision 1 is available on
    /// iOS, tvOS 12.0+, macoOS 10.14+
    #[prost(uint32, tag = "1")]
    pub revision: u32,
    ///
    /// Stores the language of the model, as specified in BCP-47 format,
    /// e.g. "en-US". See <https://tools.ietf.org/html/bcp47>
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    ///
    /// Stores the byte representation of learned model parameters
    #[prost(bytes = "vec", tag = "100")]
    pub model_parameter_data: ::prost::alloc::vec::Vec<u8>,
    ///
    /// Stores the set of output class labels
    #[prost(oneof = "text_classifier::ClassLabels", tags = "200")]
    pub class_labels: ::core::option::Option<text_classifier::ClassLabels>,
}
/// Nested message and enum types in `TextClassifier`.
pub mod text_classifier {
    ///
    /// Stores the set of output class labels
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ClassLabels {
        #[prost(message, tag = "200")]
        StringClassLabels(super::super::StringVector),
    }
}
///
/// A model which takes a single input string and outputs a
/// sequence of tokens, tags for tokens, along with their
/// locations and lengths, in the original string.
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WordTagger {
    ///
    /// Stores the resivion number for the model, revision 1 is available on
    /// iOS, tvOS 12.0+, macoOS 10.14+
    #[prost(uint32, tag = "1")]
    pub revision: u32,
    ///
    /// Stores the language of the model, as specified in BCP-47 format,
    /// e.g. "en-US". See <https://tools.ietf.org/html/bcp47>
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    ///
    /// Stores the name of tokens output. The output will be
    /// a sequence of strings that contains the tokens in the
    /// input string
    #[prost(string, tag = "20")]
    pub tokens_output_feature_name: ::prost::alloc::string::String,
    ///
    /// Stores the name of token tags output. The output will be
    /// a sequence of strings that contains the tags for each
    /// token in the input string
    #[prost(string, tag = "21")]
    pub token_tags_output_feature_name: ::prost::alloc::string::String,
    ///
    /// Stores the name of token locations output. The output will be
    /// a sequence of integers that contains the locations (indices)
    /// for each token in the input string, location starts from 0
    #[prost(string, tag = "22")]
    pub token_locations_output_feature_name: ::prost::alloc::string::String,
    ///
    /// Stores the name of token lengths output. The output will be
    /// a sequence of integers that contains the lengths for each
    /// token in the input string
    #[prost(string, tag = "23")]
    pub token_lengths_output_feature_name: ::prost::alloc::string::String,
    ///
    /// Stores the byte representation of learned model parameters
    #[prost(bytes = "vec", tag = "100")]
    pub model_parameter_data: ::prost::alloc::vec::Vec<u8>,
    ///
    /// Stores the set of output tags
    #[prost(oneof = "word_tagger::Tags", tags = "200")]
    pub tags: ::core::option::Option<word_tagger::Tags>,
}
/// Nested message and enum types in `WordTagger`.
pub mod word_tagger {
    ///
    /// Stores the set of output tags
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Tags {
        #[prost(message, tag = "200")]
        StringTags(super::super::StringVector),
    }
}
///
/// A model which takes audio signal samples as input and outputs an array of
/// preprocessed samples according to the specified preprocessing types
#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SoundAnalysisPreprocessing {
    /// Vision feature print type
    #[prost(
        oneof = "sound_analysis_preprocessing::SoundAnalysisPreprocessingType",
        tags = "20"
    )]
    pub sound_analysis_preprocessing_type: ::core::option::Option<
        sound_analysis_preprocessing::SoundAnalysisPreprocessingType,
    >,
}
/// Nested message and enum types in `SoundAnalysisPreprocessing`.
pub mod sound_analysis_preprocessing {
    /// no specific parameter
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Vggish {}
    /// Vision feature print type
    #[allow(clippy::all)]
    #[allow(clippy::pedantic)]
    #[allow(clippy::nursery)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum SoundAnalysisPreprocessingType {
        #[prost(message, tag = "20")]
        Vggish(Vggish),
    }
}
